apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerts
  labels:
    grafana_alert: "1"
data:
  alerts.yaml: |
    orgId: 1
    folder: "DL alerts"
    interval: 1m
    rules:
      - uid: node-cpu
        title: High Node CPU Usage
        condition: C
        data:
          - refId: A
            queryType: timeSeriesQuery
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
              interval: ""
              intervalFactor: 2
              legendFormat: "{{instance}}"
              refId: A
          - refId: B
            queryType: reduce
            datasourceUid: __expr__
            model:
              expression: A
              reducer: last
              type: reduce
              refId: B
          - refId: C
            queryType: threshold
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [80]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: ["B"]
                  reducer: last
                  type: query
              refId: C
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          summary: High CPU usage on node {{ $labels.instance }}
        labels:
          severity: warning