replicaCount: 1

adminUser: admin
adminPassword: admin1

persistence:
  enabled: true
  storageClassName: "local-path"
  size: 15Gi
  accessModes:
    - ReadWriteOnce

initChownData:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: DS_PROMETHEUS
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
        uid: Prometheus
        jsonData:
          tlsSkipVerify: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboardsConfigMaps:
  default: grafana-dashboards

smtp:
  existingSecret: grafana-smtp-secret
  userKey: user
  passwordKey: password

grafana.ini:
  unified_alerting:
    enabled: true
  auth.ldap:
    enabled: true
    config_file: /etc/grafana/ldap.toml

  smtp:
    enabled: true
    host: smtp.mailgun.org:587
    skip_verify: true
    from_address: postmaster@yourdomain.com 
    from_name: Grafana

extraVolumeMounts:
  - name: alert-rules
    mountPath: /etc/grafana/provisioning/alerting
  - name: ldap-config
    mountPath: /etc/grafana/ldap.toml
    subPath: ldap.toml

extraVolumes:
  - name: alert-rules
    configMap:
      name: grafana-alerts
  - name: ldap-config
    configMap:
      name: grafana-ldap-config

unifiedAlerting:
  enabled: true
  contactPoints:
    - name: email-default
      type: email
      settings:
        addresses: "alerts@example.com"        

  notificationPolicies:
    - name: default
      receiver: email-default
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 30m